### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by emicklei** [cyd01/basicweb#1]
hi,

I want to compile a basicweb binary for running the tests of the Zazkia project.
Doing so I got this error:
```
go install github.com/cyd01/basicweb@latest 
go: downloading github.com/cyd01/basicweb v0.0.0-20210820121509-9fbc3cb29e6f
# github.com/cyd01/basicweb
ld: warning: ignoring file /var/folders/cg/spvtdjhn3q9cxq6d1lzkz4b80000gn/T/go-link-3755035797/000000.o, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x64 0x86 0x01 0x00 0x00 0x00 0x00 0x00 0xA4 0x54 0x01 0x00 0x01 0x00 0x00 0x00 )
```

**Comment by cyd01** [comment]
Please find a new version at https://github.com/cyd01/basicweb (new features added).
It seems your issue is platform dependent. And unfortunately I can not reproduce it since I don't have access to any MacOS host.
But I've double checked the cross compilation to darwin architecture target on my Ubuntu device. And it works.
I'll add a new release with pre-built binaries.

**Comment by ghost** [comment]
so the problem was on an old Big Sur Mac OSx (x64) , today was able to install it using Sonoma. Not going to spent that much time on it. 
Thanks for updating the tool ( I noticed you formatted the go files :-) ).
